package com.manauwar.dcms.pojo.hibernate;
// Generated 16 Apr, 2014 12:57:57 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PersonalDetail generated by hbm2java
 */
public class PersonalDetail  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer personalDetailId;
     private Users users;
     private String passportNo;
     private Date dateOfIssue;
     private String placeOfIssue;
     private String postAppliedFor;
     private String height;
     private String weight;
     private char maritalStatus;
     private char sex;
     private String nationality;
     private Date dateOfBirth;
     private int ageInYears;
     private String certificateNo;
     private String nameOfCandidate;
     private String referenceNo;
     private Date examDate;
     private String commonRemarks;
     private String commonResult;
     private String commonReason;
     private Set laboratoryInvestigations = new HashSet(0);
     private Set medicalExaminations = new HashSet(0);

    public PersonalDetail() {
    }

	
    public PersonalDetail(Users users, String passportNo, Date dateOfIssue, String placeOfIssue, String postAppliedFor, String height, String weight, char maritalStatus, char sex, String nationality, Date dateOfBirth, int ageInYears, String certificateNo, String nameOfCandidate, String referenceNo, Date examDate) {
        this.users = users;
        this.passportNo = passportNo;
        this.dateOfIssue = dateOfIssue;
        this.placeOfIssue = placeOfIssue;
        this.postAppliedFor = postAppliedFor;
        this.height = height;
        this.weight = weight;
        this.maritalStatus = maritalStatus;
        this.sex = sex;
        this.nationality = nationality;
        this.dateOfBirth = dateOfBirth;
        this.ageInYears = ageInYears;
        this.certificateNo = certificateNo;
        this.nameOfCandidate = nameOfCandidate;
        this.referenceNo = referenceNo;
        this.examDate = examDate;
    }
    public PersonalDetail(Users users, String passportNo, Date dateOfIssue, String placeOfIssue, String postAppliedFor, String height, String weight, char maritalStatus, char sex, String nationality, Date dateOfBirth, int ageInYears, String certificateNo, String nameOfCandidate, String referenceNo, Date examDate, String commonRemarks, String commonResult, String commonReason, Set laboratoryInvestigations, Set medicalExaminations) {
       this.users = users;
       this.passportNo = passportNo;
       this.dateOfIssue = dateOfIssue;
       this.placeOfIssue = placeOfIssue;
       this.postAppliedFor = postAppliedFor;
       this.height = height;
       this.weight = weight;
       this.maritalStatus = maritalStatus;
       this.sex = sex;
       this.nationality = nationality;
       this.dateOfBirth = dateOfBirth;
       this.ageInYears = ageInYears;
       this.certificateNo = certificateNo;
       this.nameOfCandidate = nameOfCandidate;
       this.referenceNo = referenceNo;
       this.examDate = examDate;
       this.commonRemarks = commonRemarks;
       this.commonResult = commonResult;
       this.commonReason = commonReason;
       this.laboratoryInvestigations = laboratoryInvestigations;
       this.medicalExaminations = medicalExaminations;
    }
   
    public Integer getPersonalDetailId() {
        return this.personalDetailId;
    }
    
    public void setPersonalDetailId(Integer personalDetailId) {
        this.personalDetailId = personalDetailId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getPassportNo() {
        return this.passportNo;
    }
    
    public void setPassportNo(String passportNo) {
        this.passportNo = passportNo;
    }
    public Date getDateOfIssue() {
        return this.dateOfIssue;
    }
    
    public void setDateOfIssue(Date dateOfIssue) {
        this.dateOfIssue = dateOfIssue;
    }
    public String getPlaceOfIssue() {
        return this.placeOfIssue;
    }
    
    public void setPlaceOfIssue(String placeOfIssue) {
        this.placeOfIssue = placeOfIssue;
    }
    public String getPostAppliedFor() {
        return this.postAppliedFor;
    }
    
    public void setPostAppliedFor(String postAppliedFor) {
        this.postAppliedFor = postAppliedFor;
    }
    public String getHeight() {
        return this.height;
    }
    
    public void setHeight(String height) {
        this.height = height;
    }
    public String getWeight() {
        return this.weight;
    }
    
    public void setWeight(String weight) {
        this.weight = weight;
    }
    public char getMaritalStatus() {
        return this.maritalStatus;
    }
    
    public void setMaritalStatus(char maritalStatus) {
        this.maritalStatus = maritalStatus;
    }
    public char getSex() {
        return this.sex;
    }
    
    public void setSex(char sex) {
        this.sex = sex;
    }
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public int getAgeInYears() {
        return this.ageInYears;
    }
    
    public void setAgeInYears(int ageInYears) {
        this.ageInYears = ageInYears;
    }
    public String getCertificateNo() {
        return this.certificateNo;
    }
    
    public void setCertificateNo(String certificateNo) {
        this.certificateNo = certificateNo;
    }
    public String getNameOfCandidate() {
        return this.nameOfCandidate;
    }
    
    public void setNameOfCandidate(String nameOfCandidate) {
        this.nameOfCandidate = nameOfCandidate;
    }
    public String getReferenceNo() {
        return this.referenceNo;
    }
    
    public void setReferenceNo(String referenceNo) {
        this.referenceNo = referenceNo;
    }
    public Date getExamDate() {
        return this.examDate;
    }
    
    public void setExamDate(Date examDate) {
        this.examDate = examDate;
    }
    public String getCommonRemarks() {
        return this.commonRemarks;
    }
    
    public void setCommonRemarks(String commonRemarks) {
        this.commonRemarks = commonRemarks;
    }
    public String getCommonResult() {
        return this.commonResult;
    }
    
    public void setCommonResult(String commonResult) {
        this.commonResult = commonResult;
    }
    public String getCommonReason() {
        return this.commonReason;
    }
    
    public void setCommonReason(String commonReason) {
        this.commonReason = commonReason;
    }
    public Set getLaboratoryInvestigations() {
        return this.laboratoryInvestigations;
    }
    
    public void setLaboratoryInvestigations(Set laboratoryInvestigations) {
        this.laboratoryInvestigations = laboratoryInvestigations;
    }
    public Set getMedicalExaminations() {
        return this.medicalExaminations;
    }
    
    public void setMedicalExaminations(Set medicalExaminations) {
        this.medicalExaminations = medicalExaminations;
    }




}


