package com.manauwar.dcms.pojo.hibernate;
// Generated 16 Apr, 2014 12:57:57 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer usersId;
     private String userName;
     private String fullName;
     private String password;
     private Set personalDetails = new HashSet(0);

    public Users() {
    }

	
    public Users(String userName, String fullName, String password) {
        this.userName = userName;
        this.fullName = fullName;
        this.password = password;
    }
    public Users(String userName, String fullName, String password, Set personalDetails) {
       this.userName = userName;
       this.fullName = fullName;
       this.password = password;
       this.personalDetails = personalDetails;
    }
   
    public Integer getUsersId() {
        return this.usersId;
    }
    
    public void setUsersId(Integer usersId) {
        this.usersId = usersId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getPersonalDetails() {
        return this.personalDetails;
    }
    
    public void setPersonalDetails(Set personalDetails) {
        this.personalDetails = personalDetails;
    }




}


